### ISSUE TITLE
1 subscribe, multiple execute

### ISSUE THREAD

**Issue by ghost** [KallynGowdy/RxUI#35]
Hi
My goal is binding a subscriber and calling command multiple time
like in this pseudo-code I would expect `hello!` to be printed 3 times:
```
mycommand = ReactiveCommand.createFromTask( ... )
mycommand.subscribe(t => {
  console.log('hello!')
}); 

mycommand.execute()
mycommand.execute()
mycommand.execute()
```

How can I do that?

**Comment by KallynGowdy** [comment]
Yeah so to trigger a reactive command you have to call `.invoke()` on it and then subscribe to the returned observable.

For example:
```typescript
mycommand.invoke().subscribe();
mycommand.invoke().subscribe();
mycommand.invoke().subscribe();
```

**Comment by ghost** [comment]
So you are saying that it's impossible to do what I want to do?

**Comment by KallynGowdy** [comment]
Yes, you have to call subscribe on the observable returned from `.invoke()` each time you want to run the command.

**Comment by ghost** [comment]
So If I have a button that updates something, each click of the button must call `.subscribe( update_something() )` ?

**Comment by ghost** [comment]
I come from [RxCommand](https://github.com/fluttercommunity/rx_command) for Flutter where we see in their first example how it works:
```
final command = RxCommand.createSync<int, String>((myInt) => "$myInt");

command.listen((s) => print(s)); // Setup the listener that now waits for events, not doing anything

// Somwhere else
command.execute(10); // the listener will print "10"
```

**Comment by ghost** [comment]
Your RxUI is so far the most equivalent to RxCommand I found for Javascript

**Comment by KallynGowdy** [comment]
RxUI is similar to RxCommand for Flutter in that they are both inspired by [ReactiveUI](https://reactiveui.net/), but RxUI follows some of the ReactiveUI conventions a little closer.

When you call `.invoke()` on a ReactiveCommand, it [returns a cold observable](https://github.com/KallynGowdy/RxUI/blob/master/src/reactive-command.ts#L165). This means that the action will not execute until something subscribes to the observable. The reason for this is to ensure that the action does not finish before listeners are registered. This way, we can provide strong guarantees about when commands complete without having to provide special behavior to remember the results of a command.

Sample:
```typescript
// Create a command to do something.
let command = ReactiveCommand.createFromTask(...);

// Get an observable that that resolves whenever the command is completed.
let resultObservable = command.invoke();

// Subscribe to the observable.
// this will cause the command's function to be executed and the observable
// will complete when the task is done.
let subscription = resultObservable.subscribe();
```

**Comment by ghost** [comment]
the original ReactiveUI [here](https://log.paulbetts.org/using-reactivecommand/) seems to support it?
```
var command = new ReactiveCommand();

command.Subscribe(x => this.Log().Info("The number is {0}", x));

command.Execute(4);  
>>> The number is 4
```

**Comment by KallynGowdy** [comment]
That may be the original, but it is not up to date. See [this documentation page](https://reactiveui.net/docs/handbook/commands/#invoking-commands) for info on the current ReactiveCommand.
